"""add ai_summary column

Revision ID: 4a8b12f76e81
Revises: 26764c61fbda
Create Date: 2026-01-27 03:07:42.789487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8b12f76e81'
down_revision: Union[str, Sequence[str], None] = '26764c61fbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ai_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ai_summary')
    # ### end Alembic commands ###
